// app/src/ui/Confirmation.svelte
<script>
      export let title
      export let okLabel = "OK"
      export let cancelLabel = "Cancel"
      export let confirmation
      export let cancel
      export let show
</script>

<!-- 
<Dialog
  title={title}
  open={show}
>
  {confirmation}
  <Button
  label={cancelLabel}
  secondary={true}
  onClick={cancel}
/>,
<Button
  label={okLabel}
  primary={true}
  onClick={proceed}
/>

</Dialog> -->

// app/src/components/Confirmation.jsx
import React from 'react';
import Dialog from 'material-ui/Dialog';
import FlatButton from 'material-ui/FlatButton';
import { confirmable } from 'react-confirm';

import Theme from 'theme'

class Confirmation extends React.Component {

  render() {
    const {
      okLabel = 'OK',
      cancelLabel = 'Cancel',
      title,
      confirmation,
      show,
      proceed,
      dismiss,
      cancel,
      modal,
    } = this.props;

    const actions = [
      <FlatButton
        label={cancelLabel}
        secondary={true}
        onClick={cancel}
      />,
      <FlatButton
        label={okLabel}
        primary={true}
        onClick={proceed}
      />,
    ];

    return (
      <Theme>
        <Dialog
          title={title}
          actions={actions}
          modal={modal}
          open={show}
          onRequestClose={dismiss}
        >
          {confirmation}
        </Dialog>
      </Theme>
    );
  }
}

export default confirmable(Confirmation);
