// app/src/TaskJobs.tsx
import React from "react";
import { copyToClibpoard } from "./clipboard";
import { Job } from "./reducers";
import { useMessages } from "./ui/messages";

export default ({
  job,
  onKill,
  onShow,
}: {
  job: Job;
  onKill: () => void;
  onShow: () => void;
}) => {
  const { success, error } = useMessages();
  const progress = job.progress.length > 0 ? job.progress[0].progress : 0;

  return (
    <div className="resource">
      {job.status === "running" ? (
        <>
          <span
            className="status progressbar-container"
            title={`${progress * 100}%`}
          >
            <span
              style={{ right: `${(1 - progress) * 100}%` }}
              className="progressbar"
            ></span>
            <div className="status-running">{job.status}</div>
          </span>
          <i className="fa fa-skull-crossbones action" onClick={onKill} />
        </>
      ) : (
        <span className={`status status-${job.status}`}>{job.status}</span>
      )}

      <i className="fas fa-eye action" title="Details" onClick={onShow} />
      <span className="job-id" />
      <span
        className="clipboard"
        onClick={(event) =>
          copyToClibpoard(job.locator)
            .then(() => success("Job path copied"))
            .catch((e) => error("Error when copying job path: " + e))
        }
      >
        {job.taskId}
      </span>
      {job.tags.map((tag) => (
        <span key={tag[0]} className="tag">
          <span className="name">{tag[0]}</span>
          <span className="value">{tag[1]}</span>
        </span>
      ))}
    </div>
  );
};

// app/src/TaskJobs.svelte
<script>
    import { createEventDispatcher } from 'svelte'
    
    const dispatch = createEventDispatcher()
    // import CopyToClipboard from "svelte-copy-to-clipboard";
    import { success, error } from 'xpm/ui/notifications'
    export let job
    import { copyToClibpoard } from './clipboard'

    let locator
</script>

<div class="resource">
                    
    {#if job.status === "running"}
        <span class="status progressbar-container" title={`${job.progress*100}%`}>
            <span style={`right: ${(1-job.progress)*100}%`} class="progressbar"></span><div class="status-running">{job.status}</div>
        </span> 
        <i class="fa fa-skull-crossbones action" on:click={() => { dispatch('kill', job) } }/>
    {:else}
        <span class={`status status-${job.status}`}>{job.status}</span>
    {/if}

<i class="fas fa-eye action" title="Details" on:click={() =>  { dispatch('show', job) }}/>
<span class="job-id">
    <!-- <CopyToClipboard let:copy={onCopy} text={job.locator} on:copy={() => success(`Job path copied`)} on:fail={() => error(`Error copying job path`)}><span class="clipboard" on:click={onCopy}>{job.taskId}</span></CopyToClipboard></span> -->
    <span class="clipboard" on:click={event => copyToClibpoard(job.locator).then(() => success("Job path copied")).catch((e) => error("Error when copying job path: " + e))}>{job.taskId}</span>
    {#each job.tags as tag}
     <span class="tag">
            <span class="name">{tag[0]}</span><span class="value">{tag[1]}</span>
        </span>
    {/each}
</div>
