// app/src/Tasks.svelte
<script lang="ts">
    import {
        Button, 
        Modal, ModalBody, ModalFooter, ModalHeader,
        Form, FormGroup, FormText, Input, Label
    } from 'sveltestrap';

    import TaskJobs from './TaskJobs.svelte'
    import TaskDetail from './TaskDetail.svelte'
    import client from './client';
    import { info } from './ui/notifications';

    export let jobs

    // kill = (jobId: string) => {
    //     confirm('Are you sure to kill this job?').then(() => {
    //         client.send({ type: "kill", payload: jobId}, "cannot kill job " + jobId)
    //     }, () => {
    //         toast.info("Action cancelled");
    //     });
    // }

    // details = (jobId: ?string) => {
    //     if (jobId) {
    //         client.send({ type: "details", payload: jobId}, "cannot get details for job " + jobId);
    //     }
    //     this.setState({ ...this.state, jobId: jobId});
    // }

    let searchtask : RegExp | null = null
    let tags : any[] = []
    function _jobfilter(job) {
        if (searchtask && job.taskId.match(searchtask) === null) return false;

        mainloop: for(let {tag, value} of tags) {
            for(let tv of job.tags) {
                if (tv[0].search(tag) !== -1 && tv[1].toString().search(value) !== -1)
                    continue mainloop;
            }
            return false
        }

        return true;
    }
    let jobfilter = _jobfilter

    function updateTaskSearch(e) {
        const inputValue = (e.target as HTMLInputElement).value
        searchtask = inputValue !== "" ? new RegExp(inputValue) : null
        jobfilter = _jobfilter
    }

    function updateTagSearch(e) {
        const tag = (e.target as HTMLInputElement).value
        let re = /(\S+):(?:([^"]\S*)|"([^"]+)")\s*/g;
        var match : any[] | null
        tags = []
        while ((match = re.exec(tag)) !== null) {
            tags.push({ tag: match[1], value: match[2] });
        }
        console.log("Tags", tags)
        jobfilter = _jobfilter

    }


    let killJob = null;

    function cancelKill() {
        killJob = null; 
        info("Action cancelled"); 
    }

    function kill() {
        if (killJob !== null) {
            client.send({ type: "kill", payload: killJob.jobId}, "cannot kill job " + killJob.jobId)
        }
    }

    let showJob
</script>

<div id="resources">
    <div class="search">
        <div style="display: flex">
            <FormGroup>
                <Label for="searchtask">Task</Label>
                <Input id="searchtask" on:input={updateTaskSearch} placeholder="Filter task"/>
              </FormGroup>
              <FormGroup>
                <Label for="searchtags">Tags</Label>
                <Input id="searchtags" on:input={updateTagSearch} placeholder="Format tag:value..."/>
              </FormGroup>
        </div>
    </div>

    <Modal isOpen={killJob != null}>
        <ModalHeader>Are you sure?</ModalHeader>
        <ModalBody>
            Are you sure to kill job <b>{killJob.taskId}</b>?
        </ModalBody>
        <ModalFooter>
            <Button default on:click={cancelKill}>Cancel</Button>
            <Button on:click={kill}>OK</Button>
        </ModalFooter>
      </Modal>
      
      
      

    {#each jobs.ids as jobId (jobId)}
        {#if jobfilter(jobs.byId[jobId])}
            <TaskJobs job={jobs.byId[jobId]} on:kill={(event) => { killJob = event.detail }} on:show={event => { 
                showJob = showJob == event.detail ? null : event.detail
            }}/>
            {#if showJob && showJob.jobId == jobId}
                <TaskDetail job={showJob}/>
            {/if}
        {/if}
    {/each}
</div>

// app/src/Tasks.jsx
// @flow

import React, { Component } from 'react'
import { connect } from 'react-redux'

import Clipboard from 'react-clipboard.js';
import { toast } from 'react-toastify';
import { withStyles } from '@material-ui/core/styles';

import TextField from '@material-ui/core/TextField';

import { type State, type Jobs } from './reducer'
import confirm from 'util/confirm';
import client from 'client'
import Theme from 'theme'
import TaskDetail from './TaskDetail'

type StateProps = {
    jobs: Jobs
};

type Props = StateProps;
type OwnState = {
    jobId: ?string;
    searchtask: string;
    searchtagstring: string;
    searchtags: Array<{tag: string, value: string}>
}

const styles = theme => ({
  container: {
    display: 'flex',
    flexWrap: 'wrap',
  },
  textField: {
    marginLeft: theme.spacing.unit,
    marginRight: theme.spacing.unit,
    width: 200,
    padding: 10
  },
  dense: {
    marginTop: 19,
  },
  menu: {
    width: 200,
  },
});


class Tasks extends Component<Props, OwnState> {
    state = {
        searchtask: "",
        searchtagstring: "",
        searchtags: [],
        jobId: null
    }

    kill = (jobId: string) => {
        confirm('Are you sure to kill this job?').then(() => {
            client.send({ type: "kill", payload: jobId}, "cannot kill job " + jobId)
        }, () => {
            toast.info("Action cancelled");
        });
    }

    details = (jobId: ?string) => {
        if (jobId) {
            client.send({ type: "details", payload: jobId}, "cannot get details for job " + jobId);
        }
        this.setState({ ...this.state, jobId: jobId});
    }

    handleChange = name => event => {
        this.setState({ ...this.state, 
            [name]: event.target.value
        });
    };

    handleTagChange = event => {
        let tag = event.target.value;
        let re = /(\S+):(?:([^"]\S*)|"([^"]+)")\s*/g;
        var match = [];
        var tags = [];
        while ((match = re.exec(tag)) !== null) {
            // $FlowFixMe
            tags.push({ tag: match[1], value: match[2] });
        }
        this.setState({ ...this.state,
            searchtagstring: tag,
            searchtags: tags
        })
    }

    render() {
        let { jobs } = this.props;
        let { searchtask, searchtags, jobId } = this.state;

        if (jobId) {
            let job = jobs.byId[jobId];
            return <TaskDetail job={job} handleClose={() => this.setState({...this.state, jobId: null})}/>;
        }

        return <div id="resources">
            <Theme>
            <div className="search">
                <TextField
                    label="Task"
                    className="textField"
                    value={this.state.searchtask}
                    onChange={this.handleChange('searchtask')}                
                    margin="normal"
                    helperText="Task contains..."
                />
                <TextField
                    label="Tags"
                    className="textField"
                    value={this.state.searchtagstring}
                    onChange={this.handleTagChange}
                    margin="normal"
                    helperText="Search tags (format tag:value)"
                />

            </div>
            {
            jobs.ids.map(jobId => {
                let job = jobs.byId[jobId];

                if (searchtask !== "" && job.taskId.search(searchtask) === -1) {
                    return null;
                }

                mainloop: for(let {tag, value} of searchtags) {
                    for(let tv of job.tags) {
                        if (tv[0].search(tag) !== -1 && tv[1].toString().search(value) !== -1)
                            continue mainloop;
                    }
                    return null;
                }

                return <div className="resource" key={jobId}>
                    {
                        job.status === "running" ?
                        <React.Fragment>
                            <span className="status progressbar-container" title={`${job.progress*100}%`}>
                                <span style={{right: `${(1-job.progress)*100}%`}} className="progressbar"></span><div className="status-running">{job.status}</div>
                            </span> 
                            <i className="fa fa-skull-crossbones action" onClick={() => this.kill(jobId) }/>
                        </React.Fragment>
                        :
                        <span className={`status status-${job.status}`}>{job.status}</span>
                    }
                    <i className="fas fa-eye action" title="Details" onClick={() => this.details(jobId)}/>
                    <span className="job-id"><Clipboard className="clipboard" data-clipboard-text={`${job.taskId}/${job.jobId}`} onSuccess={() => toast.success(`Job path copied`)}>{job.taskId}</Clipboard></span>
                    {
                        job.tags.map((tv) => {
                            return <span key={tv[0]} className="tag">
                                <span className="name">{tv[0]}</span>
                                <span className="value">{tv[1]}</span>
                            </span>
                        })
                    }
                </div>
            })
        }</Theme></div>;
    }
}

const mapStateToProps = (state: State) : StateProps => ({
    jobs: state.jobs
})
export default connect(mapStateToProps)(withStyles(styles)(Tasks));
